name: Deploy to Staging

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy-common.yml
    with:
      environment: Staging
      target: staging
    secrets: inherit 