name: Deploy to Production

on:
  push:
    tags:
      # Format: MM-DD-YYYY-HH-MM (example: 03-14-2024-15-30)
      - '[0-1][0-9]-[0-3][0-9]-[2][0-9][0-9][0-9]-[0-2][0-9]-[0-5][0-9]'

jobs:
  deploy:
    uses: ./.github/workflows/deploy-common.yml
    with:
      environment: Production
      target: production
    secrets: inherit 