name: Deploy Ephemeral Environment

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy (defaults to current)'
        required: true
        type: string

jobs:
  deploy:
    uses: ./.github/workflows/deploy-common.yml
    with:
      environment: Ephemeral
      target: staging
      id: preview-${{ github.event.inputs.branch || github.ref_name }}
      expires: 1d
    secrets: inherit

  show-preview-url:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Display Preview URL
        run: |
          echo "# 🚀 Preview Deployment" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "🔗 [Open Preview](${{ needs.deploy.outputs.details_url }})" >> $GITHUB_STEP_SUMMARY
